#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
SECONDS=0
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
source /usr/bin/mtkvariables

function clean_1() {
	rm -f /tmp/$(basename $0)_$(whoami)
	rm -f /run/$(basename $0).pid
}

echo "$BASHPID" > /run/$(basename $0).pid
trap "clean_1; exit" 0 1 2 3 9 15
lock || exit_error

if [[ -z "$suser" ]]; then
	ayuda
fi

if [[ -z "$sshpass" ]]; then
	ayuda
fi

if [[ -z "$sshport" ]]; then
	ayuda
fi

if [[ -z "$ips" ]]; then
	ayuda
fi

if [[ -z "$cfrom" ]]; then
	ayuda
fi

if [[ -z "$cserver" ]]; then
	ayuda
fi

if [[ -z "$cport" ]]; then
	ayuda
fi

if [[ -z "$cuser" ]]; then
	ayuda
fi

if [[ -z "$cpass" ]]; then
	ayuda
fi

if [[ -z "$cdestinos" ]]; then
	ayuda
fi

if ! [[ -f ./maclist.txt ]]; then
	ayuda
fi

queversion2
if [[ "$forcecaps" == "1" ]]; then
	wcmd="caps"
fi

if [[ "$wcmd" == "caps" && "$sshport" == "22" ]]; then
	sshpass -p $sshpass $cssh $suser@$ips "caps-man access-list remove [find]"
fi

if [[ "$wcmd" == "caps" && "$sshport" != "22" ]]; then
	sshpass -p $sshpass $cssh -p $sshport $suser@$ips "caps-man access-list remove [find]"
fi

if [[ "$wcmd" == "wifi" && "$sshport" == "22" ]]; then
	sshpass -p $sshpass $cssh $suser@$ips "interface wifi access-list remove [find]"
fi

if [[ "$wcmd" == "wifi" && "$sshport" != "22" ]]; then
	sshpass -p $sshpass $cssh -p $sshport $suser@$ips "interface wifi access-list remove [find]"
fi

while read -r mac action ssid; do
		if [[ "$wcmd" == "caps" && "$sshport" == "22" ]]; then
			echo "$mac, $action, $ssid"
			sshpass -p $sshpass $cssh -n $suser@$ips "caps-man access-list add action="$action" allow-signal-out-of-range=10s comment="$ssid" disabled=no interface=all mac-address=$mac ssid-regexp="$ssid""
			echo "==================="
		fi
		if [[ "$wcmd" == "caps" && "$sshport" != "22" ]]; then
			echo "$mac, $action, $ssid"
			sshpass -p $sshpass $cssh -n -p $sshport $suser@$ips "caps-man access-list add action="$action" allow-signal-out-of-range=10s comment="$ssid" disabled=no interface=all mac-address=$mac ssid-regexp="$ssid""
			echo "==================="
		fi
		if [[ "$wcmd" == "wifi" && "$sshport" == "22" ]]; then
			echo "$mac, $action, $ssid"
			sshpass -p $sshpass $cssh -n $suser@$ips "interface wifi access-list add action="$action" comment="$ssid" disabled=no interface=all mac-address=$mac ssid-regexp="$ssid""
			echo "==================="
		fi
		if [[ "$wcmd" == "wifi" && "$sshport" != "22" ]]; then
			echo "$mac, $action, $ssid"
			sshpass -p $sshpass $cssh -n -p $sshport $suser@$ips "interface wifi access-list add action="$action" comment="$ssid" disabled=no interface=all mac-address=$mac ssid-regexp="$ssid""
			echo "==================="
		fi
done < ./maclist.txt

echo "correo"
$cmdcorreo --header "Se modificaron las ACL de acceso inalambrico el %DATE%" --body "Se modificaron las ACL de acceso inalambrico, se adjunta el archivo." --attach-type "text/plain" --attach-name "maclist.txt" --attach @/app/maclist.txt

echo "duracion $SECONDS segundos"
echo "Finalizado."
