#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
SECONDS=0
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
LOCKFD="150"
fecha=$(date +%d-%m-%Y)
back="system backup save dont-encrypt=yes"
terse="export terse compact show-sensitive"
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3"
cscp="scp -4 -C -o ConnectTimeout=3"
ctar="tar -czf"
donde="/app"
archi="/app/log.txt"
correo='swaks -4 --to $cdestinos --from $cfrom --server $cserver:$cport -tls --auth LOGIN --auth-user $cuser --auth-password $cpass --timeout 60s'

function clean_1() {
	rm -f /tmp/$(basename $0)_$(whoami)
	rm -f /run/$(basename $0).pid
}

function lock() {
	echo {LOCKFD}>$LOCKFILE
	flock -n $LOCKFD
}

function exit_error() {
	echo "ERROR: Ya hay una instancia en ejecución. Saliendo"
	exit 1
}

echo "$BASHPID" > /run/$(basename $0).pid
trap "clean_1; exit" 0 1 2 3 9 15
lock || exit_error
clear

for i in ${ips[@]}; do
	echo "IP: $i"
	echo "IP: $i" >> $archi
	echo "=========================" >> $archi
	echo "Creando Backup"
	echo "Creando Backup" >> $archi
	sshpass -p '$sshpass' $cssh -p $sshport $suser@$i "$back name=$i"
	echo "Creando Terse"
	echo "Creando Terse" >> $archi
	sshpass -p '$sshpass' $cssh -p $sshport $suser@$i "$terse file=$i"
	echo "Descargando Backup"
	echo "Descargando Backup" >> $archi
	sshpass -p '$sshpass' $cscp -P $sshport $suser@$i:$i.backup donde/$i.backup
	echo "Descargando Terse"
	echo "Descargando Terse" >> $archi
	sshpass -p '$sshpass' $cscp -P $sshport $suser@$i:$i.rsc donde/$i.rsc
done

echo "Comprimiendo"
$ctar $donde/backup-$fecha.tar.gz donde/

if [[ -z "$cserver" ]]; then
	echo "No se enviara correo."
else
	$correo --header "Subject: Respaldo de configuracion de los Mikrotik en %DATE%" --body "Se adjunta el archivo." --attach-type "application/x-compressed-tar" --attach-name "backup-$fecha.tar.gz" --attach @/app/backup-$fecha.tar.gz
fi

echo "duracion $SECONDS segundos"
echo "Finalizado."
exit 0
