#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
LOCKFD="150"
qre="qrencode -c -m 1 -s 10 -l H -d 100"
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3"
cscp="scp -4 -C -o ConnectTimeout=3"
ctar="tar -czf"
back="system backup save dont-encrypt=yes"
terse="export terse compact show-sensitive"
nocaps="7130"
donde="/app"
cmdcorreo="swaks -4 --to ${cdestinos} --from ${cfrom} --server ${cserver}:${cport} -tls --auth LOGIN --auth-user ${cuser} --auth-password ${cpass} --timeout 60s"
fecha=$(date +%d-%m-%Y)

function lock () {
	echo {LOCKFD}>"$LOCKFILE"
	flock -n "$LOCKFD"
}

function exit_error () {
	echo "ERROR: Ya hay una instancia en ejecución. Saliendo"
	exit 1
}

function ayuda () {
	echo "ERROR: faltan variables de entorno."
	exit 1
}

function queversion () {
	if [[ "$sshport" == "22" ]]; then
		wver=$(sshpass -p ${sshpass} ${cssh} ${suser}@${i} "system resource print" | grep version: | awk '{print $2}')
		xver=$(echo "${wver//.}")
	else
		wver=$(sshpass -p ${sshpass} ${cssh} -p ${sshport} ${suser}@${i} "system resource print" | grep version: | awk '{print $2}')
		xver=$(echo "${wver//.}")
	fi
	if (( $xver < $nocaps )); then
		wcmd="caps"
	else
		wcmd="wifi"
	fi
	echo "version: $xver"
	echo "comando: $wcmd"
}
